[package]
name = "async-fetcher"
version = "0.3.0-alpha.2"
repository = "https://github.com/pop-os/async-fetcher"
authors = ["Michael Aaron Murphy <mmstickman@gmail.com>"]
description = "Asynchronous file fetcher, with optional fetching based on modified times and checksums"
keywords = ["async", "file", "fetcher", "download", "parallel"]
categories = ["asynchronous", "network-programming", "web-programming::http-client"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[workspace]
members = [ "fetcher" ]

[dependencies]
async-std = "1.10.0"
async-stream = "0.3.2"
chrono = "0.4.19"
derive_more = "0.99.16"
derive_setters = "0.1.5"
derive-new = "0.5.9"
digest = "0.9.0"
filetime = "0.2.15"
futures = "0.3.17"
hex = "0.4.3"
http = "0.2.4"
http-client =  { version = "6.5.1", features = [ "native_client" ] }
log = "0.4.14"
md-5 = "0.9.1"
numtoa = "0.2.4"
remem = "0.1.0"
serde = { version = "1.0.130", features = [ "derive" ] }
sha2 = "0.9.8"
surf = "2.3.1"
thiserror = "1.0.29"
